# Generated by Django 5.2.10 on 2026-02-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tech', models.JSONField()),
                ('repo', models.URLField()),
                ('demo', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
